site_name: Cyberpunk 2077 Autohacker

nav:
  - "Documentation": index.md
  - "Development": development.md

site_dir: public

theme:
    name: material
    palette:
        scheme: slate
    favicon: media/icon.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed
